/* La lista de archivos que forman el shell de la app. Vive aparte de sw.js
   solo por tamaño; la carga `importScripts('sw-shell.js')`.

   Al agregar o quitar un archivo hay que subir VERSION en sw.js: el navegador
   detecta la actualización por el contenido de sw.js, no por el de este. */

/* './' y no 'index.html': el hosting redirige /index.html a / con un 308, y
   una respuesta con redirect guardada aquí es la que rompe la navegación en
   Safari. La raíz responde 200 directo. */
self.SHELL = [
  './',
  'manifest.json',
  'icons/icono-180.png',
  'icons/icono-192.png',
  'icons/icono-512.png',
  'css/base.css',
  'css/componentes.css',
  'css/listas.css',
  'css/overlays.css',
  'css/plan.css',
  'css/tokens.css',
  'js/api/client.js',
  'js/api/errores.js',
  'js/api/jwt.js',
  'js/api/sesion.js',
  'js/calc/ciclo-tarjeta.js',
  'js/calc/cuotas.js',
  'js/calc/deuda-tarjeta.js',
  'js/calc/dinero.js',
  'js/calc/fechas.js',
  'js/calc/plan/asignar.js',
  'js/calc/plan/linea-tiempo.js',
  'js/calc/plan/veredicto.js',
  'js/calc/saldos.js',
  'js/calc/vencimientos.js',
  'js/config.js',
  'js/iconos/render.js',
  'js/iconos/svg.js',
  'js/main.js',
  'js/movimientos/campos.js',
  'js/movimientos/formulario.js',
  'js/movimientos/orden.js',
  'js/movimientos/registrar.js',
  'js/movimientos/tipos.js',
  'js/negocio/agrupar.js',
  'js/negocio/pago-recibo.js',
  'js/pages/ajustes/categorias-form.js',
  'js/pages/ajustes/categorias.js',
  'js/pages/ajustes/cuentas-form.js',
  'js/pages/ajustes/cuentas.js',
  'js/pages/ajustes/datos.js',
  'js/pages/ajustes/fijos-variables.js',
  'js/pages/ajustes/index.js',
  'js/pages/ajustes/negocio.js',
  'js/pages/ajustes/orden.js',
  'js/pages/ajustes/plan-form.js',
  'js/pages/ajustes/respaldo.js',
  'js/pages/login.js',
  'js/pages/movimientos/filtros.js',
  'js/pages/movimientos/index.js',
  'js/pages/movimientos/vista.js',
  'js/pages/negocio/acciones.js',
  'js/pages/negocio/form.js',
  'js/pages/negocio/pendientes.js',
  'js/pages/negocio/registrar.js',
  'js/pages/pendiente.js',
  'js/pages/plan/index.js',
  'js/pages/plan/sobres.js',
  'js/pages/plan/vista.js',
  'js/pages/resumen/acciones.js',
  'js/pages/resumen/index.js',
  'js/pages/resumen/vista.js',
  'js/pages/tarjetas/compras.js',
  'js/pages/tarjetas/cuotas-form.js',
  'js/pages/tarjetas/detalle-compras.js',
  'js/pages/tarjetas/detalle.js',
  'js/pages/tarjetas/form.js',
  'js/pages/tarjetas/index.js',
  'js/pages/tarjetas/pagar.js',
  'js/pages/tarjetas/vista.js',
  'js/repos/base.js',
  'js/repos/categorias.js',
  'js/repos/compras.js',
  'js/repos/cuentas.js',
  'js/repos/movimientos.js',
  'js/repos/pagos-recibo.js',
  'js/repos/perfiles.js',
  'js/repos/plan-items.js',
  'js/repos/tarjetas.js',
  'js/router.js',
  'js/ui/ambito.js',
  'js/ui/campos.js',
  'js/ui/confirmar.js',
  'js/ui/deslizar.js',
  'js/ui/foto.js',
  'js/ui/grafica.js',
  'js/ui/lista.js',
  'js/ui/monto-input.js',
  'js/ui/pastillas.js',
  'js/ui/privacidad.js',
  'js/ui/rodillo.js',
  'js/ui/sheet-formulario.js',
  'js/ui/sheet.js',
  'js/ui/tabbar.js',
  'js/ui/texto.js',
  'js/ui/toast.js',
];
